-- Member
CREATE TABLE MEMBER_TBL
(
    ID     NUMBER PRIMARY KEY,
    NAME   NVARCHAR2(30),
    FAMILY NVARCHAR2(30)
);
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1;

-- User
CREATE TABLE USER_TBL
(
    ID     NUMBER PRIMARY KEY,
    USERNAME   NVARCHAR2(30),
    PASSWORD NVARCHAR2(30)
);
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1;

-- BOOK
CREATE TABLE BOOK_TBL
(
    ID     NUMBER PRIMARY KEY,
    NAME   NVARCHAR2(30),
    AUTHOR NVARCHAR2(30)
);
CREATE SEQUENCE BOOK_SEQ INCREMENT BY 1;

-- BORROW
CREATE TABLE BORROW_TBL
(
    ID NUMBER PRIMARY KEY,
    MEMBER_ID REFERENCES MEMBER_TBL,    -- FOREIGN KEY
    BOOK_ID REFERENCES BOOK_TBL,        -- FOREIGN KEY
    BORROW_TIMESTAMP TIMESTAMP,
    RETURN_TIMESTAMP TIMESTAMP
);
CREATE SEQUENCE BORROW_SEQ INCREMENT BY 1;

CREATE VIEW BORROW_REPORT AS
SELECT
    M.ID AS M_ID,
    M.NAME AS M_NAME,
    M.FAMILY AS M_FAMILY,
    B.ID AS B_ID,
    B.NAME AS B_NAME,
    B.AUTHOR AS B_AUTHOR,
    BR.ID AS BR_ID,
    BR.BORROW_TIMESTAMP,
    BR.RETURN_TIMESTAMP
FROM MEMBER_TBL M, BOOK_TBL B, BORROW_TBL BR
WHERE BR.MEMBER_ID = M.ID AND
      BR.BOOK_ID = B.ID
ORDER BY BR.BORROW_TIMESTAMP;