-- Member
CREATE TABLE MEMBER_TBL
(
    ID     NUMBER PRIMARY KEY,
    NAME   NVARCHAR2(30),
    FAMILY NVARCHAR2(30),
    FATHER NVARCHAR2(30),
    NATIONAL_CODE NVARCHAR2(10),
    BIRTH_DATE DATE,
    MEMBERSHIP_DATE DATE,
    DELETED number(1)
);
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1;

-- User
CREATE TABLE USER_TBL
(
    ID     NUMBER PRIMARY KEY,
    MEMBER_ID REFERENCES MEMBER_TBL,
    USERNAME   NVARCHAR2(30),
    PASSWORD NVARCHAR2(30),
    NICK_NAME NVARCHAR2(30),
    IMAGE NVARCHAR2(50),
    STATUS NUMBER(1),
    DELETED number(1)
);
CREATE SEQUENCE USER_SEQ INCREMENT BY 1;

-- BOOK
CREATE TABLE BOOK_TBL
(
    ID     NUMBER PRIMARY KEY,
    NAME   NVARCHAR2(30),
    AUTHOR NVARCHAR2(50),
    PAGES NUMBER(5),
    PUBLISHER NVARCHAR2(30),
    LANGUAGE NVARCHAR2(30),
    GENRE NVARCHAR2(50),
    ISBN NVARCHAR2(30),
    DESCRIPTION NVARCHAR2(30),
    DELETED number(1)
);
CREATE SEQUENCE BOOK_SEQ INCREMENT BY 1;

-- BORROW
CREATE TABLE BORROW_TBL
(
    ID NUMBER PRIMARY KEY,
    MEMBER_ID REFERENCES MEMBER_TBL,    -- FOREIGN KEY
    BOOK_ID REFERENCES BOOK_TBL,        -- FOREIGN KEY
    BORROW_TIMESTAMP TIMESTAMP,
    RETURN_TIMESTAMP TIMESTAMP,
    DESCRIPTION NVARCHAR2(255),
    DELETED number(1)
);
CREATE SEQUENCE BORROW_SEQ INCREMENT BY 1;

CREATE VIEW BORROW_REPORT AS
SELECT
    M.ID AS M_ID,
    M.NAME AS M_NAME,
    M.FAMILY AS M_FAMILY,
    B.ID AS B_ID,
    B.NAME AS B_NAME,
    B.AUTHOR AS B_AUTHOR,
    BR.ID AS BR_ID,
    BR.BORROW_TIMESTAMP,
    BR.RETURN_TIMESTAMP,
    BR.DESCRIPTION,
    BR.DELETED
FROM MEMBER_TBL M, BOOK_TBL B, BORROW_TBL BR
WHERE BR.MEMBER_ID = M.ID AND
      BR.BOOK_ID = B.ID
ORDER BY BR.BORROW_TIMESTAMP;

CREATE TABLE LOG_TBL(
    ID NUMBER PRIMARY KEY,
    ACTION NVARCHAR2(50),
    DATA NVARCHAR2(255),
    USER_ID REFERENCES USER_TBL,
    LOG_TIMESTAMP TIMESTAMP
);

CREATE SEQUENCE LOG_SEQ INCREMENT BY 1;
